package com.mysqldoc.common.model;

import com.mysqldoc.common.model.base.BaseDirectinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Directinfo extends BaseDirectinfo<Directinfo> {
	
}
